Update goimports script for go 1.14
Without this change, go 1.14 reports this error:

```
cannot find module providing package golang.org/x/tools/cmd/goimports: working directory is not part of a module
```

Ideally this wouldn't rely on kops being in the GOPATH but that may require updating goimports. This can happen in a followup PR