docker/centos7 - Add missing selinux-policy package
The centos7 periodic E2E jobs are currently failing [0].
Specifically, nodeup is failing to install docker and its dependencies [1] due to an additional missing dependency:

```
W1104 12:12:14.918640    2848 executor.go:128] error running task "Package/docker-ce" (9m57s remaining to succeed): error installing package "docker-ce": exit status 2: warning: /var/cache/nodeup/packages/docker-ce: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
error: Failed dependencies:
selinux-policy >= 3.13.1-192 is needed by container-selinux-2:2.68-1.el7.noarch
selinux-policy-base >= 3.13.1-192 is needed by container-selinux-2:2.68-1.el7.noarch
selinux-policy-targeted >= 3.13.1-192 is needed by container-selinux-2:2.68-1.el7.noarch
```

I reproduced this issue by manually downloading the RPMs into a centos:7 docker container and confirmed installing `selinux-policy-targeted` fixed it, but i dont have access to a centos7 cluster to confirm this at the moment. I guess we'll see how the periodic job responds once this is merged to confirm whether this fixes the issue or not.

[0] https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-aws-imagecentos7
[1] https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kops-aws-imagecentos7/1191326677003669507/artifacts/3.220.164.29/journal.log